Feature/2024 edition
dev-bcn/dev-bcn.github.io pull request #273
Opened 2023-11-26 17:37 UTC by anyulled

# 2024 Edition

Talks, workshops, speakers, job offers and communities have been removed from the navigation menu.

- [ ] Pending to confirm event date to modify the countdown
- [ ] CFP start and end date missing
- [ ] Sponsorship end dates missing. Needed to configure button enablement.

2023-12-04 12:06 UTC, jonathanvila requested changes
Temas que veo:
1. el link al summary de 2023 en realidad apunta a la presentacion de 2023 con imagenes y videos de 2022. Ahora que ya tenemos el video summary de 2023, puedes apuntar ahi?
2. faltaria el link a los videos de las charlas de 2023
3. el link a flickr no seria mejor que apunte a Albums : https://www.flickr.com/photos/devbcn/albums
4. Añadiria arriba en el home algo que diga de forma visible que el CFP y la venta de tickets empiezan el 1 de Enero de 2024
5. Añadiria en la parte de Sponsors, un boton con "Be a sponsor" y un link a mail a sponsors@devbcn.com y con el title: Sponsorship info request

2023-12-04 15:16 UTC, anyulled commented
> Temas que veo:
> 
> 1. el link al summary de 2023 en realidad apunta a la presentacion de 2023 con imagenes y videos de 2022. Ahora que ya tenemos el video summary de 2023, puedes apuntar ahi?

- [x] hecho

> 2. faltaria el link a los videos de las charlas de 2023

- [x] hecho, en el logo de Youtube

> 3. el link a flickr no seria mejor que apunte a Albums : https://www.flickr.com/photos/devbcn/albums

- [x] hecho

> 4. Añadiria arriba en el home algo que diga de forma visible que el CFP y la venta de tickets empiezan el 1 de Enero de 2024

- [x] hecho. Se ha puesto texto informativo y el primero de enero aparecerán los botones de acción.

> 5. Añadiria en la parte de Sponsors, un boton con "Be a sponsor" y un link a mail a [sponsors@devbcn.com](mailto:sponsors@devbcn.com) y con el title: Sponsorship info request

- [x] hecho, he puesto la fecha de activación del botón desde el primero de diciembre y lo he puesto para que se oculte un mes antes del evento.

2023-12-04 15:25 UTC, anyulled commented
> Los ultimos cambios perfectos. Ahora que pienso, igual faltaria link a la edicion anterior como haciamos con JBCNconf ![image](https://private-user-images.githubusercontent.com/1836434/287746603-a15afdd2-57fe-4fc4-b45c-97565f10c63c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDM4MDQsIm5iZiI6MTcwMTcwMzUwNCwicGF0aCI6Ii8xODM2NDM0LzI4Nzc0NjYwMy1hMTVhZmRkMi01N2ZlLTRmYzQtYjQ1Yy05NzU2NWYxMGM2M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTUyNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYzNTdhNTRjMjlhNzgzZDRkNDYxNGJmZjYyZjQ0NzNhMTZjYWU3NTE0MjhhMTExZjRmY2YzODU0NDRkYzU1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LtsZ6rm2yKqwKI2gxwxPLJWGV6swzAZlF2XCnCvQ2PE)

Estoy trabajando en ello justo ahora, espero subir los cambios hoy.

2023-12-12 18:05 UTC, icougil commented
Acabamos de ver estas cosas que deberíamos mirar de arreglar respecto a 2023:
- los recordings de los vídeos sólo se ven cuando accedes a la talk en concreto. ¿Se puede poner algo que en el schedule se vea de primeras que tenemos los vídeos grabados? En Sessionize tenemos el link del video, ¿se puede poner ahí directamente? ¿o mejor linkar en Sessionize al detalle del talk?
- deberíamos poder linkar desde el schedule a cada talk, ya que cada vídeo y el detalle se ve en el "detalle de cada talk"
- en el listado de talks tampoco se ve cuáles tienen recording, ¿se puede poner un 📹 o similar para ver cuáles quedaron grabadas?
- además, ¿se puede poner un link, como un botón o similar a los que tenemos en el medio de la web para linkar a nuestra playlist para que la gente pueda acceder y ver los videos grabados fácilmente?
![image](https://github.com/dev-bcn/dev-bcn.github.io/assets/2370634/87a1ba3d-ac50-4eac-b64a-f102a58643f8)

2023-12-12 19:34 UTC, anyulled commented
Vale, me pongo a trabajar en ello.

Necesitáis todo esto para diciembre? O se puede mergear esto y hacer una
nueva pr con otras cosas?

El mar, 12 dic 2023, 19:05, Nacho Cougil ***@***.***>
escribió:

> Acabamos de ver estas cosas que deberíamos mirar de arreglar respecto a
> 2023:
>
>    - los recordings de los vídeos sólo se ven cuando accedes a la talk en
>    concreto. ¿Se puede poner algo que en el schedule se vea de primeras que
>    tenemos los vídeos grabados? En Sessionize tenemos el link del video, ¿se
>    puede poner ahí directamente? ¿o mejor linkar en Sessionize al detalle del
>    talk?
>    - deberíamos poder linkar desde el schedule a cada talk, ya que cada
>    vídeo y el detalle se ve en el "detalle de cada talk"
>    - en el listado de talks tampoco se ve cuáles tienen recording, ¿se
>    puede poner un 📹 o similar para ver cuáles quedaron grabadas?
>    - además, ¿se puede poner un link, como un botón o similar a los que
>    tenemos en el medio de la web para linkar a nuestra playlist para que la
>    gente pueda acceder y ver los videos grabados fácilmente?
>    image.png (view on web)
>    <https://github.com/dev-bcn/dev-bcn.github.io/assets/2370634/87a1ba3d-ac50-4eac-b64a-f102a58643f8>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dev-bcn/dev-bcn.github.io/pull/273#issuecomment-1852553463>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAYTBIBBNN5PSHW7PGZL7DYJCMGDAVCNFSM6AAAAAA73ABZZGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJSGU2TGNBWGM>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-12-13 08:54 UTC, jonathanvila commented
yo creo que lo importante seria poder tener la web lista y accesible.

si los cambios implican mas dias, yo optaria por planchar lo que tenemos (
al menos que en la pagina de 2023 se vean los 2 botones de acceso directo a
la playlist y a flickr )

y ya en enero se pueden hacer los otros cambios

On Tue, Dec 12, 2023 at 8:34 PM Anyul Rivas ***@***.***>
wrote:

> Vale, me pongo a trabajar en ello.
>
> Necesitáis todo esto para diciembre? O se puede mergear esto y hacer una
> nueva pr con otras cosas?
>
> El mar, 12 dic 2023, 19:05, Nacho Cougil ***@***.***>
> escribió:
>
> > Acabamos de ver estas cosas que deberíamos mirar de arreglar respecto a
> > 2023:
> >
> > - los recordings de los vídeos sólo se ven cuando accedes a la talk en
> > concreto. ¿Se puede poner algo que en el schedule se vea de primeras que
> > tenemos los vídeos grabados? En Sessionize tenemos el link del video,
> ¿se
> > puede poner ahí directamente? ¿o mejor linkar en Sessionize al detalle
> del
> > talk?
> > - deberíamos poder linkar desde el schedule a cada talk, ya que cada
> > vídeo y el detalle se ve en el "detalle de cada talk"
> > - en el listado de talks tampoco se ve cuáles tienen recording, ¿se
> > puede poner un 📹 o similar para ver cuáles quedaron grabadas?
> > - además, ¿se puede poner un link, como un botón o similar a los que
> > tenemos en el medio de la web para linkar a nuestra playlist para que la
> > gente pueda acceder y ver los videos grabados fácilmente?
> > image.png (view on web)
> > <
> https://github.com/dev-bcn/dev-bcn.github.io/assets/2370634/87a1ba3d-ac50-4eac-b64a-f102a58643f8>
>
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/dev-bcn/dev-bcn.github.io/pull/273#issuecomment-1852553463>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAAYTBIBBNN5PSHW7PGZL7DYJCMGDAVCNFSM6AAAAAA73ABZZGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJSGU2TGNBWGM>
>
> > .
> > You are receiving this because you were assigned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dev-bcn/dev-bcn.github.io/pull/273#issuecomment-1852682509>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOALER2EOXINE5FHPV5VX3YJCWVTAVCNFSM6AAAAAA73ABZZGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJSGY4DENJQHE>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-12-13 10:05 UTC, anyulled commented
@jonathanvila Si, me pondré cuanto antes a arreglar el tema de los logos. Paso a contestar los comentarios de @icougil 

> Acabamos de ver estas cosas que deberíamos mirar de arreglar respecto a 2023:
> 
> * los recordings de los vídeos sólo se ven cuando accedes a la talk en concreto. ¿Se puede poner algo que en el schedule se vea de primeras que tenemos los vídeos grabados?

Tengo que mirar si es viable, porque este schedule me lo traigo con un script que provee la propia gente de sessionize y que he tenido que adaptar para ponerlo en la página.

> En Sessionize tenemos el link del video, ¿se puede poner ahí directamente? ¿o mejor linkar en Sessionize al detalle del talk?

Yo he puesto en sessionize el enlace de la grabación a cada sesión que la contiene, por tanto, todo lo que se haga allí se reflejará en la web.

> * deberíamos poder linkar desde el schedule a cada talk, ya que cada vídeo y el detalle se ve en el "detalle de cada talk"

Mismo comentario de arriba, tengo que mirar el script de sessionize y mirar si es posible.

> * en el listado de talks tampoco se ve cuáles tienen recording, ¿se puede poner un 📹 o similar para ver cuáles quedaron grabadas?

Me lo apunto para agregarlo a la página

> * además, ¿se puede poner un link, como un botón o similar a los que tenemos en el medio de la web para linkar a nuestra playlist para que la gente pueda acceder y ver los videos grabados fácilmente?

¿Dónde queréis esto?
En esta parte ya aparece toda la información multimedia de 2023 (Fotos de Flickr, lista de reproducción de Youtube

![image](https://github.com/dev-bcn/dev-bcn.github.io/assets/100741/d628bbe4-30e4-4f99-a30b-d956366b27c0)



>   ![image](https://private-user-images.githubusercontent.com/2370634/289960471-87a1ba3d-ac50-4eac-b64a-f102a58643f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjE3NjIsIm5iZiI6MTcwMjQ2MTQ2MiwicGF0aCI6Ii8yMzcwNjM0LzI4OTk2MDQ3MS04N2ExYmEzZC1hYzUwLTRlYWMtYjY0YS1mMTAyYTU4NjQzZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDk1NzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTBiNmFmMGY4MTc4N2FiMmI4NzdjZTViMjA3NmU5ZTNlMjc1ODdjYWEwNTE3OWU4ZThiNjA2OWIzNzc0YTAwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L4z1P9akN9FzfncPoM5E0H9BkGOMFTXaioOa9T91LUI)

2023-12-13 11:01 UTC, jonathanvila commented
> > * además, ¿se puede poner un link, como un botón o similar a los que tenemos en el medio de la web para linkar a nuestra playlist para que la gente pueda acceder y ver los videos grabados fácilmente?
> 
> ¿Dónde queréis esto? En esta parte ya aparece toda la información multimedia de 2023 (Fotos de Flickr, lista de reproducción de Youtube
Claro, eso aparece en la web de 2024, pero si una persona se conecta a la pagina actual,  y usando el link de arriba para ir a 2023, entonces no dispone de unos links evidentes para ir a la playlist y fotos, desde la pagina de la edicion 2023
Creo que estaria bien que si alguien va a la edicion 2023, pueda ver de entrada y bien claro los videos y fotos. Con la JBCNConf ya lo hicimos
![Screenshot 2023-12-13 at 12 00 34](https://github.com/dev-bcn/dev-bcn.github.io/assets/1836434/5c60b7dd-a684-4be8-8185-c75d05a35d47)

2023-12-13 13:27 UTC, anyulled commented
Ok, ahora lo entiendo. Me pongo con eso

El mié, 13 dic 2023, 12:01, Jonathan Vila ***@***.***>
escribió:

>
>    - además, ¿se puede poner un link, como un botón o similar a los que
>    tenemos en el medio de la web para linkar a nuestra playlist para que la
>    gente pueda acceder y ver los videos grabados fácilmente?
>
> ¿Dónde queréis esto? En esta parte ya aparece toda la información
> multimedia de 2023 (Fotos de Flickr, lista de reproducción de Youtube
> Claro, eso aparece en la web de 2024, pero si una persona se conecta a la
> pagina actual, y usando el link de arriba para ir a 2023, entonces no
> dispone de unos links evidentes para ir a la playlist y fotos, desde la
> pagina de la edicion 2023
> Creo que estaria bien que si alguien va a la edicion 2023, pueda ver de
> entrada y bien claro los videos y fotos. Con la JBCNConf ya lo hicimos
> Screenshot.2023-12-13.at.12.00.34.png (view on web)
> <https://github.com/dev-bcn/dev-bcn.github.io/assets/1836434/5c60b7dd-a684-4be8-8185-c75d05a35d47>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dev-bcn/dev-bcn.github.io/pull/273#issuecomment-1853702347>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAYTBIY2E5SOUVVZ4YTQODYJGDJJAVCNFSM6AAAAAA73ABZZGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJTG4YDEMZUG4>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-12-14 08:18 UTC, jonathanvila approved these changes
LGTM :)

2023-12-14 08:18 UTC, merged