feat: include anchor on last jbcnconf edition
dev-bcn/dev-bcn.github.io pull request #92
Opened 2023-03-16 10:07 UTC by anyulled

Closes: #91

2023-03-16 11:03 UTC, jonathanvila requested changes
Veo que si usamos el anchor, va un poco mas abajo de lo necesario ? Es decir se deberia ver "Check last JBCNConf", y a mi almenos no me aparece.

![image](https://user-images.githubusercontent.com/1836434/225597919-1b183c59-3281-4014-96de-2f234ccb90a8.png)

2023-03-17 10:57 UTC, jonathanvila requested changes
A mi me sigue funcionando igual...

![image](https://user-images.githubusercontent.com/1836434/225886075-39f627e7-e244-44ff-84a4-aae9c647fdb1.png)

2023-03-18 16:46 UTC, anyulled commented
Me parece que ahora si.

2023-03-18 17:41 UTC, jonathanvila approved these changes
LGTM :+1:

2023-03-18 17:41 UTC, merged